### Request Format 
### METHOD url

### GET user root API
GET http://localhost:3000/users

### GET user list
GET http://localhost:3000/users/get-users

### GET user by id
GET http://localhost:3000/users/get-user/62bc29c4f3fc4e68a32f2f69

### POST add new user
POST http://localhost:3000/users/add-user
Content-Type: application/json

{
    "firstName": "Jhon",
    "lastName": "Doe",
    "DOB": "1999-12-31T17:00:00.000Z",
    "username": "jhon",
    "password": "123456"
}

### PUT edit user 
PUT http://localhost:3000/users/edit-user
Content-Type: application/json

{
    "firstName": "Jhon edit",
    "lastName": "Doe",
    "DOB": "1999-12-31T17:00:00.000Z",
    "username": "jhon",
    "password": "123456"
}

### Simulate Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "jhon",
    "password": "123456"
}

### DELETE delete user
DELETE http://localhost:3000/users/delete-user/62bc3f90431d5f08be948bff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTY1MDQ2NzYsImV4cCI6MTY1NjU5MTA3NiwiYXVkIjoiNjJiYzNmOTA0MzFkNWYwOGJlOTQ4YmZmIiwiaXNzIjoibm9kZWpzLWtyaXNuYXJ1c2Rpb25vIn0.X_W-79Q-yWsCCfFmgBO0NK2ireUpN6frjXdMcPqA9S4
